CREATE DATABASE PERSON
USE PERSON
CREATE TABLE PERSON(
name VARCHAR(20),
age INT,
location VARCHAR(20)
)

INSERT INTO PERSON VALUES
('AMIR', 19, 'KATHMANDU'),
('SITA', 22, 'POKHARA'),
('RAM', 25, 'BIRATNAGAR'),
('HARI', 21, 'LALITPUR'),
('RITA', 20, 'BHAKTAPUR');

SELECT * 
FROM PERSON;