CREATE DATABASE PERSON
USE PERSON
CREATE TABLE PERSON(
name VARCHAR(20),
age INT,
location VARCHAR(20)
)

INSERT INTO PERSON VALUES
('AMIR', 19, 'KATHMANDU'),
('SITA', 22, 'POKHARA'),
('RAM', 25, 'BIRATNAGAR'),
('HARI', 21, 'LALITPUR'),
('RITA', 20, 'BHAKTAPUR');

SELECT * 
FROM PERSON;

-- ADDITION OF NEW COLUMN COLLEGE
ALTER TABLE PERSON
ADD COLLEGE VARCHAR(20);
-- DELETION OF COLUMN age
ALTER TABLE PERSON 
DROP COLUMN age;

-- RENAME OF COLUMN name to PER_NAME
EXEC sp_rename
'PERSON.name' , 'PER_NAME'
,'column';

-- RENAME OF COLUMN PERSON TO STUDENT
EXEC sp_rename
'PERSON' , 'STUDENT';
